server:
  port: 8084

spring:
  application:
    name: ms-inventario

  datasource:
    url: jdbc:mysql://localhost:3306/pontebella_inventario?useSSL=false&serverTimezone=America/Bogota&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss
    time-zone: America/Bogota

  rabbitmq:
    listener:
      simple:
        auto-startup: false

logging:
  level:
    com.pontebella.ms_inventario: DEBUG